### PR TITLE
Create filters for get all neighborhoods

### LINKED ISSUE #40: Neighborhood filter by city and state
## Issue Description
Implement a filter for Neighborhood by city and state. Both filters should be passed together because there are cities with the same name in different states.

## Tasks:
- [x] Implement filter
- [x] Update swagger
- [x] Update the tests if necessary

### PR DESCRIPTION
**Pull request by tsrrodrigues**
## Issue 
Resolves #40 

## Description
This PR created the filters city and state for get all neighborhoods route. Both filter must be passed together and the state has to be just the UF. The name of the city must be with all caracteres, special or not, and spaces correctly.

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

## How to validate?
1) sudo docker-compose up
2) sudo docker-compose exec api pytest
3) Make a GET request passing the filters to /neighborhoods.
Ex.: /neighborhoods?city=Águas Claras&state=DF.
Obs.: If you don't have the neighborhoods already in your machine got to the folder src/static and run python3 save_on_db.py. This may take a while because SP has a lot of neighborhoods, but if you just want to save the neighborhoods on DF, because it is so much fast, comment from line 25 to 34 on save_on_db.py.

### CODE REVIEW

**Review by silvasara — CHANGES_REQUESTED** [review]
Neighborhood statistics should also be returned at that endpoint. 
When there is no city in the past state, any city with that name is returned, regardless of the state:
image

**Comment by tsrrodrigues** [comment]
Now the route returns the neighborhood's statistics if it exists. Now it is possible to pass only one filter per request. If pass just the city it will return all neighborhoods that belongs to a city with that name, note that if exists two citys with that name it will return neighborhoods from both citys. If pass just the state, it will return all neightborhoods from that state.

**Review by silvasara — COMMENTED** [review]
It is still returning cities that are not from the state passed in the filter
image

**Comment by tsrrodrigues** [comment]
I'm sorry, the db.py was not added on commit. But it is fixed now.

**Review by silvasara — APPROVED** [review]

**Comment by lboaventura25** [comment]
I add a command on README to run the script and populate the database on this PR. To check, just run the command and check if has succes message.

**Review by silvasara — APPROVED** [review]

**Review by herickport — APPROVED** [review]

**Pull request merged**
